config/routes.rb
Rails.application.routes.draw do
  resources :departamentos
  get 'sessions/new'


    delete "/produtos/:id" => "produtos#destroy", as: :produto

    get 'Produtos'   => 'produtos#index'
    get "/produtos/new" => "produtos#new"
    get    'help'    => 'static_pages#help'
    get    'about'   => 'static_pages#about'
    get    'contact' => 'static_pages#contact'
    get    'signup'  => 'usuarios#new'
    get    'login'   => 'sessions#new'
    post   'login'   => 'sessions#create'
    delete 'logout'  => 'sessions#destroy'
    resources :usuarios




    get "produtos" => "produtos#index"
      get '/produtos/new' => 'produtos#new'
    root "usuarios#home"
  
   resources :produtos

end

app/models/departamento.rb
class Departamento < ActiveRecord::Base
end

app/models/produto.rb
class Produto < ActiveRecord::Base
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
before_save { self.usuario = usuario.downcase }
  VALID_USUARIO_REGEX = /\A(?=.{4,20}$)(?![_.])(?!.*[_.]{2})[a-zA-Z0-9._]+(?<![_.])\z/i
  validates :usuario, presence: true, length: {maximum: 15},
        format: { with: VALID_USUARIO_REGEX },
        uniqueness: { case_sensitive: false }


        has_secure_password
  validates :password, presence: true, length: {maximum: 255, minimum: 6}

  def Usuario.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/departamentos_controller.rb
class DepartamentosController < ApplicationController
  before_action :set_departamento, only: [:show, :edit, :update, :destroy]

  # GET /departamentos
  # GET /departamentos.json
  def index
    @departamentos = Departamento.all
  end

  # GET /departamentos/1
  # GET /departamentos/1.json
  def show
  end

  # GET /departamentos/new
  def new
    @departamento = Departamento.new
  end

  # GET /departamentos/1/edit
  def edit
  end

  # POST /departamentos
  # POST /departamentos.json
  def create
    @departamento = Departamento.new(departamento_params)

    respond_to do |format|
      if @departamento.save
        format.html { redirect_to @departamento, notice: 'Departamento was successfully created.' }
        format.json { render :show, status: :created, location: @departamento }
      else
        format.html { render :new }
        format.json { render json: @departamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /departamentos/1
  # PATCH/PUT /departamentos/1.json
  def update
    respond_to do |format|
      if @departamento.update(departamento_params)
        format.html { redirect_to @departamento, notice: 'Departamento was successfully updated.' }
        format.json { render :show, status: :ok, location: @departamento }
      else
        format.html { render :edit }
        format.json { render json: @departamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /departamentos/1
  # DELETE /departamentos/1.json
  def destroy
    @departamento.destroy
    respond_to do |format|
      format.html { redirect_to departamentos_url, notice: 'Departamento was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_departamento
      @departamento = Departamento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def departamento_params
      params.require(:departamento).permit(:nome)
    end
end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController
	def index
        @produto = Produto.all
    end
		def new
	    @produto = Produto.new
	  end

		def create
  @produto = Produto.new(produto_params)
	if @produto.save
		flash.now[:success] = "Produto criado!"
		redirect_to produtos_path
	else
		render 'new'
	end
	end

	def produto_params
		params.require(:produto).permit(:nome, :descricao, :preco, :quantidade)
	end
	 def destroy
    id = params[:id]
    Produto.destroy id
    redirect_to root_url
end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = Usuario.find_by(usuario: params[:session][:usuario].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
    redirect_to user

    else
      flash.now[:danger] = 'Combinação de usuário/senha incorreta!' # Not quite right!
            render 'new'
    end
  end

  def destroy
    log_out if logged_in?
        redirect_to root_url
    end
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_action :set_usuario, only: [:show, :edit, :update, :destroy]

  before_action :correct_user,   only: [:edit, :update]
  # GET /usuarios
  # GET /usuarios.json
  def index
    @usuarios = Usuario.all
  end

  # GET /usuarios/1
  # GET /usuarios/1.json
  def show
  end

  # GET /usuarios/new
  def new
    @usuario = Usuario.new
  end

  # GET /usuarios/1/edit
  def edit
      @usuario = Usuario.find(params[:id])
    end

  # POST /usuarios
  # POST /usuarios.json
  def create
    @usuario = Usuario.new(usuario_params)
      if @usuario.save
        log_in @usuario
        flash.now[:success] = "Usuário criado!"
        redirect_to @usuario
      else
        render 'new'
      end
  end

  # PATCH/PUT /usuarios/1
  # PATCH/PUT /usuarios/1.json
  def update
    @usuario = Usuario.find(params[:id])
    if @usuario.update_attributes(usuario_params)
      flash[:success] = "Profile updated"
      redirect_to @usuario
    else
      render 'edit'
    end
  end

  # DELETE /usuarios/1
  # DELETE /usuarios/1.json
  def destroy
    @usuario.destroy
    respond_to do |format|
      format.html { redirect_to usuarios_url, notice: 'Usuario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usuario
      @usuario = Usuario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def usuario_params
      params.require(:usuario).permit(:usuario, :password, :password_confirmation)
    end
    def correct_user
          @usuario = Usuario.find(params[:id])
          redirect_to(root_url) unless @usuario == current_user
        end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/departamentos_helper.rb
module DepartamentosHelper
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def log_in(user)
   session[:user_id] = user.id
 end

 def current_user
    @current_user ||= Usuario.find_by(id: session[:user_id])
  end

  def logged_in?
  !current_user.nil?
end

def log_out
    session.delete(:user_id)
    @current_user = nil
  end
  
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
  # Returns the Gravatar for the given usuario.
   def gravatar_for(usuario)
     gravatar_id = Digest::MD5::hexdigest(usuario.usuario.downcase)
     gravatar_url = "http://xpages.info/XPagesHome.nsf/developer_head.png"
     image_tag(gravatar_url, alt: usuario.usuario, class: "gravatar")
   end
end

app/views/departamentos/_form.html.erb
<%= form_for(@departamento) do |f| %>
  <% if @departamento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@departamento.errors.count, "error") %> prohibited this departamento from being saved:</h2>

      <ul>
      <% @departamento.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/departamentos/edit.html.erb
<h1>Editing departamento</h1>

<%= render 'form' %>

<%= link_to 'Show', @departamento %> |
<%= link_to 'Back', departamentos_path %>

app/views/departamentos/index.html.erb
<h1>Listing departamentos</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @departamentos.each do |departamento| %>
      <tr>
        <td><%= departamento.nome %></td>
        <td><%= link_to 'Show', departamento %></td>
        <td><%= link_to 'Edit', edit_departamento_path(departamento) %></td>
        <td><%= link_to 'Destroy', departamento, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Departamento', new_departamento_path %>

app/views/departamentos/new.html.erb
<h1>New departamento</h1>

<%= render 'form' %>

<%= link_to 'Back', departamentos_path %>

app/views/departamentos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @departamento.nome %>
</p>

<%= link_to 'Edit', edit_departamento_path(@departamento) %> |
<%= link_to 'Back', departamentos_path %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
       &copy Loja de camisetas LTDA-ME
  </small>
  <nav>
      <ul id="footerLinks">
    

      <li><%= link_to "Sobre",   about_path %></li>
      <li><%= link_to "Contato", contact_path %></li>
      <li> </li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <nav>
      <ul class="nav navbar-nav navbar-left">

          <li><%= link_to "Loja de Camisetas", root_path%></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
      <% if logged_in? %>
      <li><%= link_to "Produtos", produtos_path %></li>
      <% else %>
        <li><%= link_to "Home", root_path %></li>

        <% end %>

        <% if logged_in? %>
          <li><%= link_to "Usuarios", usuarios_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Conta <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Editar usuário", edit_usuario_path(current_user) %></li>

              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> Loja de camisetas </title>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
       <div class="alert alert-<%= message_type %>"><%= message %></div>
     <% end %>

      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/produtos/create.html.erb
<html>
Produto adicionado com sucesso!

<%= link_to 'Retornar', produtos_path %>
</html>

app/views/produtos/destroy.html.erb
<html>
Produto adicionado com sucesso!

<%= link_to 'Retornar', produtos_path %>
</html>

app/views/produtos/index.html.erb
<html>
<body>
<table class="table table-bordered">
    <thead>
        <tr>
            <th>Nome</th>
            <th>Descrição</th>
            <th>Preço</th>
            <th>Quantidade</th>
        </tr>
    </thead>
    <tbody>
        <% @produto.each do |produto| %>
        <tr>
            <td><%= produto.nome %></%></td>
            <td><%= produto.descricao %></%></td>
            <td><%= produto.preco %></%></td>
            <td><%= produto.quantidade %></%>
              <% if current_user.admin? %>
            <td><%= button_to "Remover", produto,
                        method: :delete,
                        class: "btn btn-danger",
                        data: { confirm: "Tem certeza que deseja remover?" } %></td>

            </td>
            <% end %>  
        </tr>
        <% end %>
    </tbody>
</table>
</body>
<% if current_user.admin? %>
<li><%= link_to "Adicionar Produtos", '/produtos/new' %></li>
<% end %>
</html>

app/views/produtos/new.html.erb
<% if current_user.admin? %>
<html>
<body>
  <div class="row">
    <div class="col-md-7 col-md-offset-1">
  <%=form_for(@produto) do |f| %>

  <%= f.label :nome, "Nome" %>
  <%= f.text_field :nome, class: 'form-control' %>

  <%= f.label :descricao, "Descrição" %>
  <%= f.text_field :descricao, class: 'form-control' %>
  <%= f.label :quantidade, "Quantidade" %>
  <%= f.text_field :quantidade, class: 'form-control' %>

  <%= f.label :preco, "Preço" %>
  <%= f.text_field :preco, class: 'form-control' %>

<%= f.submit "Criar produto", class: "btn btn-primary" %>

<% end %>
</div>
</div>
</body>
<%= link_to 'Retornar', produtos_path %>
</html>
<% else %>

<div class="center jumbotron">
  <h1>Loja de camisetas</h1>

  <h2>
    Opss, se perdeu?
  </h2>

</div>
<div class="form-group">
    <%= f.label :departamento %>
    <%= f.collection_select :departamento_id, @departamentos, :id, :nome %>

</div>

<% end %>

app/views/shared/_error_messages.html.erb
<% if @usuario.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@usuario.errors.count, "error") %>.
    </div>
    <ul>
    <% @usuario.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/usuarios/_form.html.erb
<% if logged_in? %>
<div class="center jumbotron">
  <h1>Loja de camisetas</h1>

  <h2>
    Opss, se perdeu?
  </h2>

</div>

<% else %>
<% provide(:title, 'Novo registro') %>
<h1>Novo registro</h1>

<div class="row">
  <div class="col-md-3 col-md-offset-3">
    <%= form_for(@usuario) do |f| %>
    <%= render 'shared/error_messages' %>

      <%= f.label :usuario, "Usuário" %>
      <%= f.text_field :usuario, class: 'form-control' %>

      <%= f.label :password, "Senha" %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmar senha" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Criar minha conta", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

<% end %>

app/views/usuarios/edit.html.erb
<% provide(:title, "Editar usuario") %>
<h1>Editar usuário</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@usuario) do |f| %>
      <%= render 'shared/error_messages' %>


      <%= f.label :usuario, "Usuário" %>
      <%= f.text_field :usuario, class: 'form-control' %>

      <%= f.label :password, "Senha" %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmação" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Salvar mudanças", class: "btn btn-primary" %>
    <% end %>


  </div>
</div>

app/views/usuarios/home.html.erb
<div class="center jumbotron">
  <h1>Loja de camisetas</h1>

  <h2>
    Seja bem vindo!
  </h2>
  <% if logged_in? %>
  <% else %>
  <%= link_to "Registrar-se!", signup_path, class: "btn btn-lg btn-primary" %>

  <% end %>
</div>

app/views/usuarios/index.html.erb
<% provide(:title, 'All usuarios') %>
<h1>Todos os usuários</h1>

<ul class="usuarios">
  <% @usuarios.each do |usuario| %>
    <li>

      <%= link_to usuario.usuario, usuario %>
    </li>
  <% end %>
</ul>

app/views/usuarios/new.html.erb
<%= render 'form' %>

<%= link_to 'Retornar', root_path %>

app/views/usuarios/show.html.erb
<% provide(:title, @usuario.usuario) %>
<h1>
  <%= gravatar_for @usuario %>
  <%= @usuario.usuario %>
</h1>